spring.datasource.url=jdbc:postgresql://dpg-d81kgjl0lvsc73f0j6rg-a.ohio-postgres.render.com:5432/inventory_db_4ge4

spring.datasource.username=inventory_db_4ge4_user

spring.datasource.password=tymrsLR8Wgukl6lPZaaI1VQrNnvL1COg

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
